-- ============================================
-- FIREBIRD PROTOCOL - GAME CONTENT
-- Версия: Firebird 5.0 Embedded
-- ============================================

-- Таблица: game_days
CREATE TABLE game_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    day_number INTEGER NOT NULL,
    title VARCHAR(100),
    description VARCHAR(500),
    is_playable SMALLINT DEFAULT 1,
    alternative_activity VARCHAR(50),
    CONSTRAINT uk_game_days UNIQUE (role, day_number)
);

-- Таблица: emails
CREATE TABLE emails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id INTEGER,
    sender VARCHAR(100) NOT NULL,
    sender_email VARCHAR(100),
    subject VARCHAR(200) NOT NULL,
    body VARCHAR(5000) NOT NULL,
    email_type VARCHAR(20),
    is_required SMALLINT DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    unlock_condition VARCHAR(100)
);

-- Таблица: quests
CREATE TABLE quests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id INTEGER,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sql_template VARCHAR(1000) NOT NULL,
    expected_rows INTEGER,
    expected_columns VARCHAR(100),
    difficulty VARCHAR(20),
    time_limit_minutes INTEGER DEFAULT 0,
    sql_skills_required VARCHAR(200),
    story_flags_set VARCHAR(500),
    story_flags_required VARCHAR(500),
    moral_choice SMALLINT DEFAULT 0,
    consequences VARCHAR(500)
);

-- Таблица: sql_commands
CREATE TABLE sql_commands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    firebird_specific SMALLINT DEFAULT 0,
    introduced_day INTEGER,
    times_used INTEGER DEFAULT 0,
    last_used_day INTEGER DEFAULT 0
);

-- Таблица: player_progress
CREATE TABLE player_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    save_slot INTEGER DEFAULT 1,
    user_role VARCHAR(20),
    current_day INTEGER DEFAULT 1,
    violations INTEGER DEFAULT 0,
    trust_level INTEGER DEFAULT 50,
    flags_unlocked VARCHAR(2000),
    quests_completed VARCHAR(2000),
    endings_unlocked VARCHAR(2000),
    total_playtime_minutes INTEGER DEFAULT 0,
    last_saved TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица: player_choices
CREATE TABLE player_choices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id INTEGER,
    choice_type VARCHAR(50),
    choice_value VARCHAR(500),
    day_id INTEGER,
    consequences_applied SMALLINT DEFAULT 0,
    choice_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица: news_articles
CREATE TABLE news_articles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id INTEGER,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    category VARCHAR(50),
    is_visible SMALLINT DEFAULT 1,
    visibility_condition VARCHAR(100),
    publish_date DATE
);

-- Таблица: employee_dossiers
CREATE TABLE employee_dossiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR(100) NOT NULL,
    job_position VARCHAR(100),
    department VARCHAR(50),
    hire_date DATE,
    status VARCHAR(20),
    dossier_text VARCHAR(1000),
    unlock_condition VARCHAR(100),
    is_mysterious SMALLINT DEFAULT 0
);

-- Таблица: random_events
CREATE TABLE random_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(100) NOT NULL,
    event_type VARCHAR(50),
    min_day INTEGER,
    max_day INTEGER,
    trigger_chance DOUBLE PRECISION,
    effect_description VARCHAR(500),
    can_occur_multiple SMALLINT DEFAULT 0
);

-- Таблица: endings
CREATE TABLE endings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ending_name VARCHAR(100) NOT NULL,
    ending_type VARCHAR(50),
    role_required VARCHAR(20),
    conditions_required VARCHAR(500),
    description VARCHAR(1000),
    is_secret SMALLINT DEFAULT 0
);

-- ============================================
-- ИНДЕКСЫ
-- ============================================

CREATE INDEX idx_emails_day ON emails(day_id);
CREATE INDEX idx_quests_email ON quests(email_id);
CREATE INDEX idx_news_day ON news_articles(day_id);

-- ============================================
-- НАЧАЛЬНЫЕ ДАННЫЕ
-- ============================================

-- SQL команды
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('SELECT', 'basics', 0, 1, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('FROM', 'basics', 0, 1, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('WHERE', 'filtering', 0, 1, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('ORDER BY', 'filtering', 0, 2, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('GROUP BY', 'aggregates', 0, 3, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('COUNT', 'aggregates', 0, 3, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('AVG', 'aggregates', 0, 4, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('SUM', 'aggregates', 0, 4, 0);

-- Дни (пример для дня 1-3)
INSERT INTO game_days (id, role, day_number, title, description, is_playable) VALUES (1, 'employee', 1, 'Первый день', 'Добро пожаловать в НИИ "Файербёрд"', 1);
INSERT INTO game_days (id, role, day_number, title, description, is_playable) VALUES (2, 'employee', 2, 'Странности', 'Коллеги ведут себя подозрительно', 1);
INSERT INTO game_days (id, role, day_number, title, description, is_playable) VALUES (3, 'employee', 3, 'Статистика', 'Руководство запрашивает отчёт', 1);

-- Письма (пример)
INSERT INTO emails (id, day_id, sender, sender_email, subject, body, email_type, is_required, sort_order) VALUES 
(1, 1, 'Отдел кадров', 'hr@nii-firebird.gov', 'Добро пожаловать', 'Уважаемый сотрудник! Поздравляем с первым рабочим днём.', 'quest', 1, 1);

-- Задания (пример)
INSERT INTO quests (id, email_id, title, description, sql_template, expected_rows, expected_columns, difficulty, sql_skills_required) VALUES 
(1, 1, 'Ознакомление с базой', 'Выполните запрос для получения списка сотрудников', 'SELECT * FROM employees', 5, 'id,name,department,salary', 'easy', 'SELECT,FROM');

COMMIT;