-- ============================================
-- FIREBIRD PROTOCOL - GAME CONTENT
-- Версия: Firebird 5.0 Embedded
-- ============================================

-- Таблица: game_days
CREATE TABLE game_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    day_number INTEGER NOT NULL,
    title VARCHAR(100),
    description VARCHAR(500),
    is_playable SMALLINT DEFAULT 1,
    alternative_activity VARCHAR(50),
    CONSTRAINT uk_game_days UNIQUE (role, day_number)
);

-- Таблица: emails
CREATE TABLE emails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id INTEGER,
    sender VARCHAR(100) NOT NULL,
    sender_email VARCHAR(100),
    subject VARCHAR(200) NOT NULL,
    body VARCHAR(5000) NOT NULL,
    email_type VARCHAR(20),
    is_required SMALLINT DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    unlock_condition VARCHAR(100)
);

-- Таблица: quests
CREATE TABLE quests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id INTEGER,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    sql_template VARCHAR(1000) NOT NULL,
    expected_rows INTEGER,
    expected_columns VARCHAR(100),
    difficulty VARCHAR(20),
    time_limit_minutes INTEGER DEFAULT 0,
    sql_skills_required VARCHAR(200),
    story_flags_set VARCHAR(500),
    story_flags_required VARCHAR(500),
    moral_choice SMALLINT DEFAULT 0,
    consequences VARCHAR(500)
);

-- Таблица: sql_commands
CREATE TABLE sql_commands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    firebird_specific SMALLINT DEFAULT 0,
    introduced_day INTEGER,
    times_used INTEGER DEFAULT 0,
    last_used_day INTEGER DEFAULT 0
);

-- Таблица: player_progress
CREATE TABLE player_progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    save_slot INTEGER DEFAULT 1,
    user_role VARCHAR(20),
    current_day INTEGER DEFAULT 1,
    violations INTEGER DEFAULT 0,
    trust_level INTEGER DEFAULT 50,
    flags_unlocked VARCHAR(2000),
    quests_completed VARCHAR(2000),
    endings_unlocked VARCHAR(2000),
    total_playtime_minutes INTEGER DEFAULT 0,
    last_saved TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица: player_choices
CREATE TABLE player_choices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_id INTEGER,
    choice_type VARCHAR(50),
    choice_value VARCHAR(500),
    day_id INTEGER,
    consequences_applied SMALLINT DEFAULT 0,
    choice_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица: news_articles
CREATE TABLE news_articles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id INTEGER NOT NULL,
    category VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    author VARCHAR(100),
    is_permanent SMALLINT DEFAULT 0,
    unlock_flag VARCHAR(100),
    related_quest_id INTEGER
);

-- Таблица: employee_dossiers
CREATE TABLE employee_dossiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR(100) NOT NULL,
    job_position VARCHAR(100),
    department VARCHAR(50),
    hire_date DATE,
    status VARCHAR(20),
    dossier_text VARCHAR(1000),
    unlock_condition VARCHAR(100),
    is_mysterious SMALLINT DEFAULT 0
);

-- Таблица: random_events
CREATE TABLE random_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(100) NOT NULL,
    event_type VARCHAR(50),
    min_day INTEGER,
    max_day INTEGER,
    trigger_chance DOUBLE PRECISION,
    effect_description VARCHAR(500),
    can_occur_multiple SMALLINT DEFAULT 0
);

-- Таблица: endings
CREATE TABLE endings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ending_name VARCHAR(100) NOT NULL,
    ending_type VARCHAR(50),
    role_required VARCHAR(20),
    conditions_required VARCHAR(500),
    description VARCHAR(1000),
    is_secret SMALLINT DEFAULT 0
);

-- Таблица: player_query_log
CREATE TABLE player_query_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_text VARCHAR(10000),
    day_id INTEGER,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Таблица: employees
CREATE TABLE employees (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100),
    department VARCHAR(50),
    salary INTEGER
);

-- ============================================
-- ИНДЕКСЫ
-- ============================================

CREATE INDEX idx_emails_day ON emails(day_id);
CREATE INDEX idx_quests_email ON quests(email_id);
CREATE INDEX idx_news_day ON news_articles(day_id);
CREATE INDEX idx_news_category ON news_articles(category);

-- ============================================
-- НАЧАЛЬНЫЕ ДАННЫЕ
-- ============================================

-- SQL команды
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('SELECT', 'basics', 0, 1, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('FROM', 'basics', 0, 1, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('WHERE', 'filtering', 0, 1, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('ORDER BY', 'filtering', 0, 2, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('GROUP BY', 'aggregates', 0, 3, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('COUNT', 'aggregates', 0, 3, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('AVG', 'aggregates', 0, 4, 0);
INSERT INTO sql_commands (command_name, category, firebird_specific, introduced_day, times_used) VALUES ('SUM', 'aggregates', 0, 4, 0);

-- Дни (пример для дня 1-3)
INSERT INTO game_days (id, role, day_number, title, description, is_playable) VALUES (1, 'employee', 1, 'Первый день', 'Добро пожаловать в НИИ "Файербёрд"', 1);
INSERT INTO game_days (id, role, day_number, title, description, is_playable) VALUES (2, 'employee', 2, 'Странности', 'Коллеги ведут себя подозрительно', 1);
INSERT INTO game_days (id, role, day_number, title, description, is_playable) VALUES (3, 'employee', 3, 'Статистика', 'Руководство запрашивает отчёт', 1);

-- Письма (пример)
INSERT INTO emails (id, day_id, sender, sender_email, subject, body, email_type, is_required, sort_order) VALUES
(1, 1, 'Отдел кадров', 'hr@nii-firebird.gov', 'Добро пожаловать', 'Уважаемый сотрудник! Поздравляем с первым рабочим днём в НИИ "Файербёрд".' || ASCII_CHAR(10) || ASCII_CHAR(10) || 'Ваш пропуск активирован. Рабочее место оборудовано терминалом с доступом к базе данных сотрудников.' || ASCII_CHAR(10) || ASCII_CHAR(10) || 'Ознакомьтесь с расписанием и ожидайте дальнейших указаний.', 'info', 1, 1);
INSERT INTO emails (id, day_id, sender, sender_email, subject, body, email_type, is_required, sort_order) VALUES
(2, 1, 'Начальник отдела', 'chief@nii-firebird.gov', 'Первое задание: список сотрудников', 'Новичок, прежде чем приступать к работе, мне нужно знать, кто здесь работает.' || ASCII_CHAR(10) || ASCII_CHAR(10) || 'Составьте полный список сотрудников через терминал. Запрос должен вернуть все записи из таблицы employees.' || ASCII_CHAR(10) || ASCII_CHAR(10) || 'Подсказка: используйте SELECT * FROM employees.', 'quest', 1, 2);

-- Задания (пример)
INSERT INTO quests (id, email_id, title, description, sql_template, expected_rows, expected_columns, difficulty, sql_skills_required) VALUES 
(1, 2, 'Ознакомление с базой', 'Выполните запрос для получения списка сотрудников', 'SELECT * FROM employees', 5, 'id,name,department,salary', 'easy', 'SELECT,FROM');

-- Сотрудники (пример)
INSERT INTO employees (id, name, department, salary) VALUES (1, 'Иванов Иван', 'IT', 75000);
INSERT INTO employees (id, name, department, salary) VALUES (2, 'Петрова Мария', 'HR', 65000);
INSERT INTO employees (id, name, department, salary) VALUES (3, 'Сидоров Алексей', 'IT', 80000);
INSERT INTO employees (id, name, department, salary) VALUES (4, 'Козлова Анна', 'Бухгалтерия', 60000);
INSERT INTO employees (id, name, department, salary) VALUES (5, 'Морозов Дмитрий', 'Аналитика', 70000);

-- Новости (тестовые данные)
-- Новости (каждый день новые)
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(1, 1, 'news', 'Планёрка', 'Сегодня в 9:00 состоится общая планёрка. Явка обязательна.', 'Администрация', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(2, 2, 'news', 'Новый сотрудник', 'В отдел аналитики принят новый сотрудник. Добро пожаловать!', 'Отдел кадров', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(3, 3, 'news', 'Проверка', 'На следующей неделе ожидается проверка из министерства.', 'Дирекция', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(4, 4, 'news', 'Премии', 'По итогам квартала лучшим сотрудникам будут выданы премии.', 'Бухгалтерия', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(5, 5, 'news', 'Выходной', 'В субботу работа не проводится. Выходной.', 'Профком', 0);

-- Wiki-статьи (постоянные)
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(6, 1, 'wiki', 'Основы SQL', 'SELECT — выборка данных' || ASCII_CHAR(10) || 'FROM — источник данных' || ASCII_CHAR(10) || 'WHERE — условие фильтрации' || ASCII_CHAR(10) || 'ORDER BY — сортировка', 'Справочная', 1);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(7, 1, 'wiki', 'Что такое Firebird?', 'Firebird — реляционная СУБД с открытым кодом. Поддерживает стандарт SQL.', 'Справочная', 1);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(8, 1, 'wiki', 'НИИ Файербёрд', 'Научно-исследовательский институт основан в 1975 году. Занимается разработкой информационных систем.', 'Справочная', 1);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(9, 1, 'wiki', 'История СССР', 'Союз Советских Социалистических Республик образован в 1922 году.', 'Справочная', 1);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(15, 1, 'wiki', 'Внимание: Терминал', 'Встроенный терминал проверяет ваш отчёт, но может иногда ошибаться, так что будьте более внимательны в работе. Система автоматической проверки использует упрощённый алгоритм и не гарантирует 100% точности.', 'Справочная', 1);

-- Доска объявлений (с дня 3)
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(10, 3, 'board', 'Пропуск', 'Найден пропуск на 3 этаж. Обратитесь в отдел кадров.', 'Охрана', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(11, 4, 'board', 'Обмен', 'Обменяю билет в театр на два в кино. Звонить после 18:00.', 'Петров', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(12, 5, 'board', 'Потерялась кошка', 'Рыжая кошка с ошейником. Откликнется на кличку "База".', 'Сидорова', 0);

-- Юмор (с дня 5)
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(13, 5, 'humor', 'Про программиста', 'Программист и база данных сидят за одним столом. Кто из них главный? Тот, у кого права администратора!', 'Коллектив', 0);
INSERT INTO news_articles (id, day_id, category, title, content, author, is_permanent) VALUES
(14, 5, 'humor', 'SQL-шутка', 'SELECT * FROM users WHERE drunk = TRUE — вернёт всю компанию!', 'Аноним', 0);

COMMIT;